/*
 * SOA LAB 1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ifmo.soalab2.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.xml.bind.annotation.XmlRootElement;

import javax.validation.Valid;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * ProductWithoutID
 */
@XmlRootElement(name = "ProductWithouID")
public class ProductWithoutID implements Serializable {

    private String name;
    private ProductCoordinates coordinates;
    private Date creationDate;
    private Float price;
    private Long manufactureCost;

    private UnitOfMeasure unitOfMeasure;
    private ProductOrganization organization;

    public ProductWithoutID(String name, ProductCoordinates coordinates, Date creationDate, Float price, Long manufactureCost, UnitOfMeasure unitOfMeasure, ProductOrganization organization) {
        this.name = name;
        this.coordinates = coordinates;
        this.creationDate = creationDate;
        this.price = price;
        this.manufactureCost = manufactureCost;
        this.unitOfMeasure = unitOfMeasure;
        this.organization = organization;
    }

    /**
     * Get name
     *
     * @return name
     **/

    @Schema(example = "Sandwich", description = "")
    @Size(min = 1)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get coordinates
     *
     * @return coordinates
     **/

    @Schema(description = "")
    @Valid
    public ProductCoordinates getCoordinates() {
        return coordinates;
    }

    public void setCoordinates(ProductCoordinates coordinates) {
        this.coordinates = coordinates;
    }



    /**
     * Get creationDate
     *
     * @return creationDate
     **/
    @Schema(description = "")
    @Valid
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public ProductWithoutID price(Float price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     * minimum: 1
     *
     * @return price
     **/
    @Schema(example = "250", description = "")
    @DecimalMin("1")
    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public ProductWithoutID manufactureCost(Long manufactureCost) {
        this.manufactureCost = manufactureCost;
        return this;
    }

    /**
     * Get manufactureCost
     *
     * @return manufactureCost
     **/
    @Schema(example = "150", description = "")
    public Long getManufactureCost() {
        return manufactureCost;
    }

    public void setManufactureCost(Long manufactureCost) {
        this.manufactureCost = manufactureCost;
    }



    /**
     * Get unitOfMeasure
     *
     * @return unitOfMeasure
     **/
    @Schema(example = "PCS", description = "")
    public UnitOfMeasure getUnitOfMeasure() {
        return unitOfMeasure;
    }

    public void setUnitOfMeasure(UnitOfMeasure unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }

    /**
     * Get organization
     *
     * @return organization
     **/
    @Schema(description = "")
    @Valid
    public ProductOrganization getOrganization() {
        return organization;
    }

    public void setOrganization(ProductOrganization organization) {
        this.organization = organization;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProductWithoutID productWithoutID = (ProductWithoutID) o;
        return Objects.equals(this.name, productWithoutID.name) &&
                Objects.equals(this.coordinates, productWithoutID.coordinates) &&
                Objects.equals(this.creationDate, productWithoutID.creationDate) &&
                Objects.equals(this.price, productWithoutID.price) &&
                Objects.equals(this.manufactureCost, productWithoutID.manufactureCost) &&
                Objects.equals(this.unitOfMeasure, productWithoutID.unitOfMeasure) &&
                Objects.equals(this.organization, productWithoutID.organization);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, coordinates, creationDate, price, manufactureCost, unitOfMeasure, organization);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProductWithoutID {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
        sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    manufactureCost: ").append(toIndentedString(manufactureCost)).append("\n");
        sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
        sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
